### ISSUE TITLE
Add github pages for easier preview / usage of the helper

### ISSUE THREAD

**Issue by tordans** [abdurrahmanyildiz/geojson-feature-merger#1]
Hi, it would be helpful if you activated github pages for this repo and added a link to the html file in the repositories description. — Thanks for the tool, it helped me as a test case for a script I am working on.

**Comment by ardayildizcs** [comment]
Hi, it is a great idea. I am going to create a page as soon as possible.
You are welcome and also thank you for the contribution.

**Comment by ardayildizcs** [comment]
Tool is now available on Github Pages. 
You can visit on : https://abdurrahmanyildiz.github.io/geojson-feature-merger/feature-merger.html 
Readme updated.
Thanks for this nice contrubution
